config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :movies do
    get :search, on: :collection
  end
  # Defines the root path route ("/")
  root "movies#index"
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :actors_movies
  has_many :movies, through: :actors_movies
end

app/models/actors_movie.rb
class ActorsMovie < ApplicationRecord
  belongs_to :actor
  belongs_to :movie
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :locations_movies
  has_many :movies, through: :locations_movies
end

app/models/locations_movie.rb
class LocationsMovie < ApplicationRecord
  belongs_to :location
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :actors_movies
  has_many :actors, through: :actors_movies
  has_many :locations_movies
  has_many :locations, through: :locations_movies
  has_many :reviews

  def average_rating
    reviews.average(:stars)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.joins(:reviews).group(:id).order('AVG(reviews.stars) DESC')
    
  end

  def search
    if params[:actor_name].present?
      @movies = Movie.joins(:actors).where(actors: { name: params[:actor_name] })
    else
      @movies = Movie.joins(:reviews).group(:id).order('AVG(reviews.stars) DESC')
    end
    respond_to do |format|
      format.js
      format.html { render 'index' }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_movies_list.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Average Rating</th>
      <th>Reviews</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.title, movie_path(movie) %></td>
        <td><%= movie.average_rating.round(2) %></td>
        <td><%= movie.reviews.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/index.html.erb
<h1>Movies</h1>
<%= form_with url: search_movies_path, method: :get, data: { remote: true } do |form| %>
  <%= form.text_field :actor_name %>
  <%= form.submit "Search" %>
<% end %>

<%= render 'movies/movies_list', movies: @movies %>

app/views/movies/search.js.erb
$("#movies-list").html("<%= j (render partial: 'movies/movies_list', locals: { movies: @movies }) %>");